### ISSUE TITLE
can i use this package to print html element not pictures

### ISSUE THREAD

**Issue by biloo-dev** [Imfdj/electron-vue-printer#1]
hi thank you for your job 
i want to use it to print component 

![2020-11-23_105209](https://user-images.githubusercontent.com/37638323/99948684-149c9c00-2d7a-11eb-9fc8-924e6bcd007b.png)

**Comment by Imfdj** [comment]
You can use "html2canvas" or "dom-to-image" to get  base64-encoded of dom.  then can use print([src,base64]:String). hope this helps！

**Comment by biloo-dev** [comment]
Thank you for the reply and I will try to work with it thanks
